// Step 11: Updating a Root Layout for Your Next.js App
// Now, let’s focus on building the foundational layout for our Next.js app.
// This Root Layout (layout.tsx) will serve as the 
// backbone of our application structure.
// // src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; 
import Providers from "./providers"; // We bring in the Provider component that we will create later for session capture

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Now, let's build our Root Layout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // This Root Layout serves as the canvas for our application's visual structure
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          <div className="z-10 items-center font-mono text-sm lg:flex">
            {/* Now, let's provide context with our Providers component */}
            <Providers>
              {children}
            </Providers>
          </div>
        </main>
      </body>
    </html>
  );
}